# Workflow name
name: Taskaru App Backend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building multi-platform images (recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/taskaru-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          PORT: ${{ vars.PORT }}
          MONGO_URI: ${{ vars.MONGO_URI }}
          DB_URI: ${{ vars.DB_URI }}
          CERT_FOLDER: ${{ vars.CERT_FOLDER }}
          CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
          CLIENT_URL: ${{ vars.CLIENT_URL }}
          GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}

      # Optional: Add a notification step here if needed,
      # e.g., sending a message to Slack or Discord that a new image is ready.
      # - name: Notify Deployment Repo
      #   run: echo "New taskaru-backend image pushed. Trigger deployment workflow manually or via webhook."
